language: c

addons:
    apt_packages:
        - binutils-mingw-w64
        - gcc-mingw-w64

os:
    - linux
    - osx

compiler:
    - clang
    - gcc
    - i686-w64-mingw32-gcc

env:
    - CONFIG_OPTS=""
    - CONFIG_OPTS="shared"
    - CONFIG_OPTS="-d"

matrix:
    exclude:
        - os: osx
          compiler: i686-w64-mingw32-gcc

before_script:
    - if [ "$CC" == i686-w64-mingw32-gcc ]; then
          export CROSS_COMPILE=${CC%%gcc}; unset CC;
          ./Configure mingw $CONFIG_OPTS;
      else
          ./config $CONFIG_OPTS;
      fi

script:
    - make
    - if [ -z "$CROSS_COMPILE" ]; then make test; fi

notifications:
    recipient:
        - openssl-commits@openssl.org
    email:
        on_success: change
        on_failure: always
